name: 'Upstream Sync'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
      
      - name: Sync upstream changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 添加上游仓库并获取数据
          git remote add upstream https://github.com/cmliu/edgetunnel.git
          git fetch upstream
          
          # 将上游 main 分支合并到你的 main 分支
          git merge upstream/main --no-edit
          
          # 推送到你的仓库
          git push origin main
